@URL = http://localhost:8080

# @name login
POST {{URL}}/auth/login HTTP/1.1
content-type: application/json

{
    "username": "john",
    "password": "12345"
}

###

@authToken = {{login.response.body.access_token}}

GET {{URL}}/auth/profile HTTP/1.1
Authorization: Bearer {{authToken}}

###

GET {{URL}}/contracts HTTP/1.1
Authorization: Bearer {{authToken}}