version: '3'
services:
  web: 
    restart: always
    build: 
      context: ./packages/web-service
      dockerfile: Dockerfile
    ports: 
      - 54050:3000
      
  users:
    restart: always
    build:
      context: ./packages/users-service
      dockerfile: Dockerfile
    # volumes:
    #   - ./users.service:/app
    ports:
      - 54060:3000
    depends_on:
      - mongodb
    environment:
      - API_KEY=72c49b83-9b86-490b-94cb-8eb0b6f9dc40
      - CONNECTION_STRING=mongodb://mongodb:27017/zabawt

### AUTH

  auth:
    restart: always
    build:
      context: ./packages/auth-service
      dockerfile: Dockerfile
    ports:
      - 54070:3000
    environment:
      - JWT_SECRET=e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
      - USERS_SERVICE_URL=http://users-api:3000/users/validate
      - USERS_API_KEY=72c49b83-9b86-490b-94cb-8eb0b6f9dc40

### CONTRACTS

  contracts:
    restart: always
    build:
      context: ./packages/contracts-service
      dockerfile: Dockerfile
    ports: 
      - 54080:3000
    depends_on:
      - mongodb
    environment:
      - CONNECTION_STRING=mongodb://mongodb:27017/zabawt


      ### DB
  mongodb: # each service should have their own persistance layer, this is being done only for showcase
    image: mongo
    depends_on:
      - mongo_seed_users
      - mongo_seed_contracts
    ports: 
      - 27017:27017

  mongo_seed_users:
    build:
      context: ./mongo-seed-users
      dockerfile: Dockerfile

  mongo_seed_contracts:
    build:
      context: ./mongo-seed-contracts
      dockerfile: Dockerfile