version: '3'
services:
  web: 
    restart: always
    build: 
      context: ./packages/web-service
      dockerfile: Dockerfile
    depends_on:
      - contracts
      - auth
    ports: 
      - 54050:3000
    environment:
      - TZ=Poland
      
  users:
    restart: always
    build:
      context: ./packages/users-service
      dockerfile: Dockerfile
    ports:
      - 54060:3000
    depends_on:
      - mongousers
    environment:
      - API_KEY=72c49b83-9b86-490b-94cb-8eb0b6f9dc40
      - CONNECTION_STRING=mongodb://mongousers:27017/users

### AUTH

  auth:
    restart: always
    build:
      context: ./packages/auth-service
      dockerfile: Dockerfile
    ports:
      - 54070:3000
    environment:
      - JWT_SECRET=e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
      - JWT_EXPIRE=900s
      - USERS_SERVICE_URL=http://users:3000/users/validate
      - USERS_API_KEY=72c49b83-9b86-490b-94cb-8eb0b6f9dc40
      - TZ=Poland

### CONTRACTS

  contracts:
    restart: always
    build:
      context: ./packages/contracts-service
      dockerfile: Dockerfile
    ports: 
      - 54080:3000
    depends_on:
      - mongocontracts
    environment:
      - CONNECTION_STRING=mongodb://mongocontracts:27017/contracts
      - JWT_SECRET=e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855

      ### DB
  mongousers: # each service should have their own persistance layer, this is being done only for showcase
    image: mongo
    ports: 
      - 27017:27017

  mongocontracts: 
    image: mongo
    ports: 
      - 27018:27017

  mongoseed_users:
    build:
      context: ./mongo-seed-users
      dockerfile: Dockerfile
    depends_on:
      - mongousers
      
  mongoseed_contracts:
    build:
      context: ./mongo-seed-contracts
      dockerfile: Dockerfile
    depends_on: 
      - mongocontracts