version: '3'
services:
  web: 
    restart: always
    build: 
      context: .
      dockerfile: ./web/Dockerfile
    volumes:
      - ./web:/app
    ports: 
      - 54060:3000
  # users:
  #   restart: always
  #   build:
  #     context: .
  #     dockerfile: Users/Dockerfile
  #   volumes:
  #     - ./Users:/app/users
  #   ports:
  #     - 54070:3000
  #   depends_on:
  #     - mongodb
  #   environment:
  #    - NODE_ENV=production
  #    - CONNECTION_STRING=mongodb://mongodb:27017/zabawt
  contracts:
    restart: always
    build:
      context: .
      dockerfile: ./contracts/Dockerfile
    volumes:
      - ./contracts:/app
    ports: 
      - 54080:3000
    depends_on:
      - mongodb
    environment:
     - NODE_ENV=production
     - CONNECTION_STRING=mongodb://mongodb:27017/zabawt
  mongodb: # each service should have their own persistance layer, this is being done only for showcase
    image: mongo
    ports: 
      - 27017:27017
  mongo_seed:
    build: ./mongo-seed
    links:
      - mongodb