version: '3'
services:
  web: 
    restart: always
    build: 
      context: .
      dockerfile: Web/Dockerfile
    volumes:
      - /web:/app/web
    ports: 
      - 80:3000
  users:
    restart: always
    build:
      context: .
      dockerfile: Users/Dockerfile
    volumes:
      - /users:/app/users
    ports:
      - 54070:3000
  contracts:
    restart: always
    build:
      context: .
      dockerfile: Contracts/Dockerfile
    volumes:
      - /contracts:/app/contracts
    ports: 
      - 54080:3000
    depends_on:
      - mongodb_contracts
    environment:
     - NODE_ENV=production
     - CONNECTION_STRING=mongodb://mongodb_contracts:27017/zabawt
  mongodb_contracts:
    image: mongo
    ports: 
      - 27017:27017
  mongo_seed:
    build: ./contracts/seed
    links:
      - mongodb_contracts