@URL = http://localhost:3000/contracts
@JWT = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI1YWM0ZDYzMy01MzMyLTRkYjktYTQyMS1lZjQ4ZmZhODI3NDciLCJuYW1lIjoiTmVkIEtlbmF3YXkiLCJpYXQiOjE1MTYyMzkwMjJ9.zPIXECvRrqGAyJ4zEwvNM3r6P7BAACtxkVj1WKLNWGg

# @name create
POST {{URL}} HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{JWT}}

{
      "from": "{{$datetime iso8601}}",
      "userId" : "{{$guid}}"
}

###

POST {{URL}} HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{JWT}}

{
      "from": "{{$datetime iso8601}}"
}

###
GET {{URL}}/{{create.response.body.id}} HTTP/1.1
Authorization: Bearer {{JWT}}

###
GET {{URL}} HTTP/1.1
Authorization: Bearer {{JWT}}