@URL = http://localhost:54080/contracts
@JWT = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI1YWM0ZDYzMy01MzMyLTRkYjktYTQyMS1lZjQ4ZmZhODI3NDciLCJuYW1lIjoiTmVkIEtlbmF3YXkiLCJpYXQiOjE1MTYyMzkwMjJ9.Zy8AEkGDp7dbXjowlmnd9vcPfH4b3mZDz9UTpEkt1bc
@USER_MANY = b1defb25-55b3-462a-beae-fb8c785a2b95
# @name create
POST {{URL}} HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{JWT}}

{
      "from": "{{$datetime iso8601}}",
      "userId" : "{{$guid}}"
}

###
# with fixed user ID
POST {{URL}} HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{JWT}}

{
      "from": "{{$datetime iso8601}}",
      "userId" : "{{USER_MANY}}"
}


###
# Invalid post request
POST {{URL}} HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{JWT}}

{
      "from": "{{$datetime iso8601}}"
}

###
GET {{URL}}/{{create.response.body.id}} HTTP/1.1
Authorization: Bearer {{JWT}}

###
GET {{URL}} HTTP/1.1
Authorization: Bearer {{JWT}}

###

GET {{URL}}/users/{{USER_MANY}}
Authorization: Bearer {{JWT}}